Desafio no relacionamento das bases do Relatório Operacional
splor-mg/notas pull request #7
Opened 2023-04-18 19:19 UTC by hslinhares

2023-08-04 21:41 UTC, fjuniorr requested changes

2023-08-04 21:41 UTC, fjuniorr commented on 20231804T160439/index.md
> +Para exemplificar os métodos de empilhamento (concatenate) e linktable nesta nota, são utilizados como amostra, as bases de Execução da Despesa, Crédito Inicial e Autorizado, e Aprovação de Cota Orça
Acho que vale a pena usar bases da Receita, Crédito Inicial e Execução que vão exemplificar as mesmas questões de forma mais simples.

2023-08-04 21:41 UTC, fjuniorr commented on 20231804T160439/index.md
> +LOAD ANO,
Acho que vale a pena reduzir o número de colunas inseridas pra facilitar a visualização tanto dos scripts quanto das imagens.

Isso inclusive facilita se valer a pena criar alguns exemplos ilustrativos dos dados em si, tipo esse do livro [Star Schema The Complete Reference](https://www.amazon.com/Schema-Complete-Reference-Christopher-Adamson/dp/0071744320):

![image](https://github.com/splor-mg/notas/assets/4969445/e5b86ef3-d463-480e-8de2-adbb24e3cc1e)

2023-08-04 21:41 UTC, fjuniorr commented on 20231804T160439/index.md
> +# Introdução
Algumas referências interessantes que encontrei pra ajudar nessa contextualização inicial:

- [The Soul of the Data Warehouse, Part 2: Drilling Across - Kimball Group](https://www.kimballgroup.com/2003/04/the-soul-of-the-data-warehouse-part-two-drilling-across/)
- [Consolidated Fact Table | Kimball Dimensional Modeling Techniques](https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/consolidated-fact-table/)
- [No Detail Too Small - DecisionWorks Consulting](https://decisionworks.com/2003/10/no-detail-too-small/)

2023-08-10 13:35 UTC, fjuniorr commented on 20231804T160439/index.md
> +Para exemplificar os métodos de empilhamento (concatenate) e linktable nesta nota, são utilizados como amostra, as bases de Execução da Despesa, Crédito Inicial e Autorizado, e Aprovação de Cota Orça
@hslinhares pra gente sempre ter mais de uma base na mesma granularidade acho que faz sentido a gente inserir uma base de Restos a Pagar também.

2023-10-23 19:47 UTC, fjuniorr commented
@labanca seu review ainda não veio!

2023-10-24 18:42 UTC, labanca reviewed
Nota muito boa!

2023-10-24 22:21 UTC, fjuniorr commented on 20231804T160439/index.qmd
> +O método de relacionamento *[linktable](QlikView_Technical_Brief-Concatenate-and-Link-tables.pdf)* consiste empilhar em uma única tabela, chamada `tabela link` ou *`linktable`*, todas as variáveis em
> Eu entendi essa parte, mas acho que ele está dizendo algo que pode ser interpretado como empilhar "somente as colunas que existem em todas as tabelas fatos ao mesmo tempo"

Pra linktable com chave única essa afirmação é verdadeira. Mas definitivamente faz sentido falar que pra linktable com múltiplas chaves o método de relacionamento consiste em empilhar em uma única tabela variáveis em comum a pelo menos duas tabelas fato.

2023-12-04 19:36 UTC, hslinhares commented on 20231804T160439/index.qmd
> +O método de relacionamento *[linktable](QlikView_Technical_Brief-Concatenate-and-Link-tables.pdf)* consiste empilhar em uma única tabela, chamada `tabela link` ou *`linktable`*, todas as variáveis em
20231804T160439/index.qmd

2023-12-04 19:41 UTC, merged